In [26]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
iris = datasets.load_iris()

iris = datasets.load_iris()
data, labels = iris.data, iris.target
df = pd.DataFrame(iris.data, columns=iris.feature_names)


train_data, test_data, train_labels, test_labels = train_test_split(data, labels, 
                       train_size=0.8,
                       test_size=0.2,
                       random_state=12)

from sklearn.preprocessing import StandardScaler
df1 = df.copy()
scaler = StandardScaler()
train_data_scaled=scaler.fit_transform(train_data)
print(train_data_scaled.std(axis=0))
print(train_data_scaled)

from sklearn.model_selection import GridSearchCV
param_grid = {'n_neighbors': np.arange(1, 10)}
grid = GridSearchCV(KNeighborsClassifier(), param_grid, cv = 5)
grid.fit(train_data_scaled, train_labels)


print("best params :",grid.best_params_)
print("best validation score:",grid.best_score_)
test_data_scaled=scaler.transform(test_data)
bestmodel=grid.best_estimator_
print("Score on test:",bestmodel.score(test_data_scaled, test_labels))

"""from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

cv = KFold(n_splits=5, random_state=1, shuffle=True)
model = KNeighborsClassifier()
scores = cross_val_score(model, train_data, train_labels, scoring='accuracy', cv=cv)
print(scores.mean())"""





[1. 1. 1. 1.]
[[-9.23010404e-01  9.92828352e-01 -1.37449891e+00 -1.19654889e+00]
 [-4.32373645e-01 -1.45676683e+00 -5.72707879e-02 -2.75283018e-01]
 [ 5.48899875e-01 -3.43314477e-01  1.03087418e+00  7.77592269e-01]
 [-4.32373645e-01  2.55166165e+00 -1.37449891e+00 -1.32815830e+00]
 [-6.43960747e-02 -7.88695420e-01  7.44520243e-01  9.09201679e-01]
 [-1.87055265e-01  2.99704259e+00 -1.31722812e+00 -1.06493948e+00]
 [-3.09714455e-01 -3.43314477e-01 -1.14541576e-01  1.19545215e-01]
 [-4.32373645e-01 -1.45676683e+00 -2.54333389e-16 -1.43673607e-01]
 [-6.43960747e-02  2.10628071e+00 -1.48904049e+00 -1.32815830e+00]
 [ 1.80922305e-01 -1.90214778e+00  1.14541576e-01 -2.75283018e-01]
 [-9.23010404e-01 -1.23407636e+00 -4.58166303e-01 -1.43673607e-01]
 [-1.04566959e+00  7.70137880e-01 -1.25995733e+00 -1.06493948e+00]
 [-1.78162473e+00 -3.43314477e-01 -1.37449891e+00 -1.32815830e+00]
 [-9.23010404e-01  1.66089977e+00 -1.31722812e+00 -1.19654889e+00]
 [-1.29098797e+00 -1.20624005e-01 -1.37449891e+0

"from sklearn.model_selection import KFold\nfrom sklearn.model_selection import cross_val_score\n\ncv = KFold(n_splits=5, random_state=1, shuffle=True)\nmodel = KNeighborsClassifier()\nscores = cross_val_score(model, train_data, train_labels, scoring='accuracy', cv=cv)\nprint(scores.mean())"